#!/bin/sh

# Displays recent commit history
# Usage: githist [<max=15>]

max="$1"
if [ -z "$max" ]; then
    max=15
fi

git log -n "$max" --pretty=format:'%C(yellow)%h %C(cyan)%ad %Cgreen%an%C(auto)%d %Creset%s' --date=iso8601 --graph
